services:
  flask:
    build: .
    env_file: .env
    depends_on:
      - ollama
    volumes:
      - ./output:/app/output
    networks:
      - backend

  ollama:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./litellm_config.yaml:/config.yaml
    command: ["--config", "/config.yaml"]
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
    networks:
      - backend

networks:
  backend:
    driver: bridge