model_list:
  - model_name: llama3.1
    litellm_params:
      model: ${MODEL_LLM}
      api_base: ${MODEL_API}
      api_key: null
      custom_llm_provider: ollama

  - model_name: mxbai-embed-large
    litellm_params:
      model: ${MODEL_EMBEDDING}
      api_base: ${MODEL_EMBEDDING_API}
      api_key: null
      custom_llm_provider: ollama

